version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
  app-1:
    container_name: crypto-app-1
    build: .
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=-Dspring.r2dbc.url=r2dbc:postgresql://db-master:5432/postgres
  app-2:
    container_name: crypto-app-2
    build: .
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS=-Dspring.r2dbc.url=r2dbc:postgresql://db-slave-1:5432/postgres -Ddb.init=false
  app-3:
    container_name: crypto-app-3
    build: .
    ports:
      - 8083:8080
    environment:
      - JAVA_OPTS=-Dspring.r2dbc.url=r2dbc:postgresql://db-slave-2:5432/postgres -Ddb.init=false
  db-master:
    container_name: crypto-db-master
    image: 'bitnami/postgresql:10'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=repl_postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
  db-slave-1:
    container_name: crypto-db-slave-1
    image: 'bitnami/postgresql:10'
    ports:
      - 5433:5432
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=repl_postgres
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
  db-slave-2:
    container_name: crypto-db-slave-2
    image: 'bitnami/postgresql:10'
    ports:
      - 5434:5432
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_postgres
      - POSTGRESQL_REPLICATION_PASSWORD=repl_postgres
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres