version: "3.8"
services:
  app:
    build: .
    ports:
      - 8080:8080
  db:
    image: postgres:10.1
    container_name: crypto_app_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432